config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect("/report/new")
  get "/report/", to: "report#index"
  get "/report/new", to: "report#new"
  post "/report/new", to: "report#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :job_group
end

app/models/job_group.rb
class JobGroup < ApplicationRecord
end

app/models/payroll_entry.rb
class PayrollEntry < ApplicationRecord
  default_scope { order(employee_id: :asc, pay_period_start: :asc) }
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :employee
  belongs_to :job_group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/report_controller.rb
class ReportController < ApplicationController

  def index
    @payroll_entries = PayrollEntry.all
    render "index"
  end

  def new
    render "new"
  end

  def create
    report_id = ReportHelper.get_report_id(time_entry_params)

    if TimeEntry.where(report_id: report_id).exists?
      flash.now[:danger] = "Failed to process Timesheet (duplicate report id)"
      render "new"
    else
      ReportHelper.process_csv(time_entry_params)
      redirect_to report_path
    end
  end

  private
    # strong parameters
    def time_entry_params
      params.require(:time_entries).permit(:csv)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/report_helper.rb
require 'csv'

module ReportHelper

  def self.get_report_id(params)
    raw_report_id = `tail -n 1 "#{params[:csv].path}"`
    CSV.parse(raw_report_id)[0][1]
  end

  def self.process_csv(params)
    job_groups = {}
    employees = {}
    report_id = get_report_id(params)

    CSV.foreach(params[:csv].path, headers: true, header_converters: :symbol) do |row|
      job_group = job_groups[row[:job_group]] \
      || job_groups[row[:job_group]] = JobGroup.find_by(code: row[:job_group])

      employee = employees[row[:employee_id]] \
        || employees[row[:employee_id]] = Employee.find_or_create_by(employee_id: row[:employee_id])

      unless row[:date] == "report id"
        ActiveRecord::Base.transaction do
          time_entry = TimeEntry.create!(workday: row[:date], hours_worked: row[:hours_worked],
            employee: employee, job_group: job_group, report_id: report_id)

          period_start, period_end = calculate_pay_period(time_entry.workday)

          payroll_entry = PayrollEntry.find_or_create_by!(employee_id: employee.employee_id,
            pay_period_start: period_start, pay_period_end: period_end)

          payroll_entry.update!(wages: payroll_entry.wages + (time_entry.hours_worked * time_entry.job_group.hourly_wage))
        end
      end
    end
  end

  def self.calculate_pay_period(date)
    if (1..15).include?(date.day)
      [date.beginning_of_month, date.change(day: 15)]
    else
      [date.change(day: 16), date.end_of_month]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SE ChallengePayroll</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/report/_form.html.erb
<%= form_for(:time_entries , remote: false) do |form| %>
  <%= form.file_field :csv %>
  <%= form.submit "Upload", class: "btn btn-primary" %>
<% end %>

app/views/report/index.html.erb
<div class="row" style="padding-top: 2rem;">
  <div class="col-6">
    <h1>Report</h1>
  </div>
  <div class="col-6">
    <%= link_to "Upload New Timesheet", report_new_path, class: "btn btn-primary" %>
  </div>
  <div class="col-12"  style="padding-top: 2rem;">
    <table class="table">
      <thead>
        <th>Employee ID</th>
        <th>Pay Period Start</th>
        <th>Pay Period End</th>
        <th>Wages</th>
      </thead>
      <tbody>
        <% @payroll_entries.each do |entry| %>
          <tr>
            <td><%= entry.employee_id %></td>
            <td><%= entry.pay_period_start %></td>
            <td><%= entry.pay_period_end %></td>
            <td><%= entry.wages %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/report/new.html.erb
<div class="row">
  <div class="mx-auto" style="padding-top: 5rem;">
    <h1>Upload Timesheet</h1>
  </div>
</div>
<div class="row">
  <div class="mx-auto" style="padding-top: 2rem;">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <%= render partial: "form" %>
  </div>
</div>
<div class="row">
  <div class="mx-auto" style="padding-top: 2rem;">
    <%= link_to "Report", report_path %>
  </div>
</div>